# Generated by Django 4.0 on 2021-12-20 10:14

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

def load_data(apps, schema_editor):
    Station = apps.get_model('stations', 'Station')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
    for obj in objects['elements']:
        try:
            objType = obj['type']
            if objType == 'node':
                tags = obj['tags']
                name = tags.get('name', 'no-name')
                longitude = obj.get('lon', 0)
                latitude = obj.get('lat', 0)
                location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                Station(name=name, location=location).save()
        except KeyError:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]


DATA_FILENAME = 'export.json'